# 사이트 정보
title: Hwaly's Blog
author: Byeonghwa Yeon
nickname: hwaly
description: 화리 블로그입니다.
keywords: [화리, 프론트엔드, hwaly, front-end]
url: https://hwaly.github.io
baseurl: ""
github_username: hwaly
timezone: Asia/Seoul

markdown: kramdown
highlighter: rouge

# 메뉴
#menu:
#  Tags: /tags/

collections:
  drafts:
    permalink: /:categories/:year/:month/:day/:title/
    output: true
  posts:
    permalink: /:categories/:year/:month/:day/:title/
    output: true

defaults:
- scope:
    path: _drafts
    type: drafts
  values:
    layout: posts
- scope:
    path: _posts
    type: posts
  values:
    layout: posts

sass:
  style: compressed

plugins:
- jekyll-babel

exclude:
- Gemfile
- Gemfile.lock
- node_modules
- package.json
- .gitignore
- README.md
