# 사이트 정보
title: "Hwaly's Blog"
description: "화리 블로그입니다."
keywords: "화리, hwaly, frontend, javascript, html, css"
url: "https://hwaly.github.io"
baseurl: "/"
github_username: "hwaly"

author: "Byeonghwa Yeon"
nickname: "hwaly"

# 메뉴
nav:
  home: "/"


# Build settings
markdown: kramdown
highlighter: rouge

paginate: 5
paginate_path: "page:num"
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - .gitignore
  - README.md
