# 사이트 정보
title: "Hwaly's Blog"
description: "화리 블로그입니다."
keywords: "화리, hwaly, frontend, javascript, html, css"
url: "https://hwaly.github.io"
baseurl: ""
github_username: "hwaly"

author: "Byeonghwa Yeon"
nickname: "hwaly"

# 메뉴
#menu:
#  Tags: "/tags.html"

collections:
  drafts:
    permalink: /:categories/:year/:month/:day/:title/
    output: true
  posts:
    permalink: /:categories/:year/:month/:day/:title/
    output: true

defaults:
- scope:
    path: _drafts
    type: drafts
  values:
    layout: post
- scope:
    path: _posts
    type: posts
  values:
    layout: post

# Build settings
markdown: kramdown
highlighter: rouge

sass:
  style: compressed

#paginate: 5
#paginate_path: "page:num"

plugins:
- jekyll-babel

#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- package.json
- .gitignore
- README.md
